### ISSUE TITLE
Uncaught Error: Could not find module root given file: "undefined". Do you have a `package.json` ...

### ISSUE THREAD

**Issue by malarkannaninvention** [willwhitney/hydrogen#134] opened 2015-11-13 06:54 UTC
[Enter steps to reproduce below:]

1. updated to 1.2.0 from 1.1.0
2. uninstalled hydrogen and reinstalled it.

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.6.5

### Stack Trace

Uncaught Error: Could not find module root given file: "undefined". Do you have a `package.json` file? 

```
At /Users/malar/.atom/packages/Hydrogen/node_modules/zmq/node_modules/bindings/bindings.js:159

Error: Could not find module root given file: "undefined". Do you have a `package.json` file? 
    at Function.getRoot (/Users/malar/.atom/packages/Hydrogen/node_modules/zmq/node_modules/bindings/bindings.js:159:13)
    at bindings (/Users/malar/.atom/packages/Hydrogen/node_modules/zmq/node_modules/bindings/bindings.js:55:32)
    at Object.<anonymous> (/Users/malar/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/malar/.atom/packages/Hydrogen/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/malar/.atom/packages/hydrogen/lib/main.coffee:4:7)
    at Object.<anonymous> (/Users/malar/.atom/packages/hydrogen/lib/main.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:14)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:215:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:158:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:170:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:301:17
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:664:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:26
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:37.8.0 settings-view:open (atom-text-editor.editor.is-focused)
  3x -0:54.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "Hydrogen": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
autocomplete-paths, v1.0.2
autocomplete-python, v0.10.3
git-diff-details, v0.21.0
haskell-ghc-mod, v1.1.2
haskell-pointfree, v0.1.2
language-haskell, v1.5.0
language-matlab, v0.1.1
minimap, v4.16.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by themiguelamador** [comment] 2015-11-13 09:20
Same error here. [

Enter steps to reproduce below:]

1. Updated Atom from 1.1 to 1.2
2. If reinstall 1.1 no error, but it is automaticly updated to 1.2 as soon as I close it the first time.

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.6.5


### Stack Trace

Failed to activate the Hydrogen package

```
At Could not find module root given file: "undefined". Do you have a `package.json` file? 

Error: Could not find module root given file: "undefined". Do you have a `package.json` file? 
    at Function.getRoot (/Users/miguel/.atom/packages/Hydrogen/node_modules/bindings/bindings.js:159:13)
    at bindings (/Users/miguel/.atom/packages/Hydrogen/node_modules/bindings/bindings.js:55:32)
    at Object.<anonymous> (/Users/miguel/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/miguel/.atom/packages/Hydrogen/node_modules/zmq/index.js:2:18)
```

### Commands

```
     -0:02.0 hydrogen:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-clojure",
      "language-c",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-toml",
      "language-yaml",
      "color-picker",
      "markdown-mindmap",
      "markdown-pdf",
      "background-tips",
      "dev-live-reload",
      "language-java",
      "language-javascript",
      "metrics",
      "Sublime-Style-Column-Selection",
      "language-r",
      "markdown-preview-plus",
      "package-sync",
      "script"
    ],
    "packagesWithKeymapsDisabled": [
      "script",
      "git-plus",
      "git-projects",
      "imdone-atom",
      "latex",
      "project-manager"
    ],
    "audioBeep": false,
    "projectHome": "/Users/miguel/Google\\ Drive/Development/Projects"
  },
  "Hydrogen": {}
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.6.5
auto-detect-indentation, v0.4.2
browser-plus, v0.0.54
file-icons, v1.6.11
highlight-selected, v0.10.1
imdone-atom, v1.1.56
language-julia, v0.4.1
local-history, v3.2.3
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
project-manager, v2.6.5
repl-term, v0.2.2
terminal-plus, v0.14.0

# Dev
No dev packages
```

**Comment by n-riesco** [comment] 2015-11-18 19:31
See #135

**Comment by willwhitney** [comment] 2015-11-28 00:34
Closing as dupe of #135.

**Closed by willwhitney** 2015-11-28 00:34 UTC
