### ISSUE TITLE
Plots are a bit constrained

### ISSUE THREAD

**Issue by rgbkrk** [willwhitney/hydrogen#3] opened 2015-05-18 04:20 UTC
![screenshot 2015-05-17 23 20 23](https://cloud.githubusercontent.com/assets/836375/7674352/4ab29bf2-fceb-11e4-9e2d-3a7381ff1857.png)

**Comment by rgbkrk** [comment] 2015-05-18 04:29
On a separate note (and not the fault of Hydrogen), matplotlib should still by default respond with rich output if it can for all frontends. :tired_face:

**Comment by willwhitney** [comment] 2015-05-18 15:24
Hmm, it's weird that it placed that bubble there. It should have been placed at the end of the selected area (by `.plot()`) and been much wider. Not sure why this is getting cut off.

I found that limiting the size of the bubbles was necessary to keep large images/videos/stacktraces from filling the entire screen — any clever ideas about a better solution?

**Comment by rgbkrk** [comment] 2015-05-18 17:13
The way I was going to lay it out was with a separate pane or tab that can be moved around (the way Atom script was initially created). It would be nice to be able to dock it. One flow that I've considered is a swipable collection of outputs though I *really* like the output next to run line UI.

**Comment by willwhitney** [comment] 2015-05-18 17:35
Yeah, I've been playing around with designs for throwing the output into a
separate pane (maybe more like a normal REPL pane, maybe something else)
but I haven't landed on anything I really like yet.

I will be adding support for opening multiline results in a new Editor
pane, but that doesn't improve images. Maybe with some fiddling the UI for
images will be good enough as-is.

**Comment by rgbkrk** [comment] 2015-05-18 22:10
At least for me, I'm going to want a pane so that I can interact with widgets, Bokeh plots, etc.

There's always the option of making alternative UIs (in separate packages), but sharing common components. Beyond just the Jupyter stuff, some of the code I looked over in Hydrogen is the same stuff we had to do in [atom script](https://github.com/rgbkrk/atom-script) for contextual running of code (selection, whole file, temp file). Making a Jupyter package for Atom has been high on my list to break away from the script package, so I'm super excited you've gotten this going.

**Comment by willwhitney** [comment] 2015-05-19 20:32
I don't think this particular bug is happening any more, so I'll close the issue.

Still thinking about ways to build a good two-pane experience though.

**Comment by rgbkrk** [comment] 2015-05-19 20:55
After the latest upgrade, I'm still seeing a plot like this:

![screenshot 2015-05-19 15 54 30](https://cloud.githubusercontent.com/assets/836375/7713755/530918b2-fe3f-11e4-91db-89e635f455de.png)

This is probably because two mimetypes are being displayed instead of just `image/png`.

**Comment by willwhitney** [comment] 2015-05-19 21:38
Ah, I see what's going on. The kernel is sending two separate messages, an `execute_result` and a `display_data`.  Showing both of them is OK (actually necessary; hard to determine which results to ignore, and doing it wrong is deadly). The issue is that the image was being displayed inline instead of block, so it got pushed . Fix coming.

**Comment by willwhitney** [comment] 2015-05-19 21:40
Closed by 6592b3b6bd00ee134d968f18d15e7c48ce8f9bd6

**Closed by willwhitney** 2015-05-19 21:40 UTC
Labels: bug
