### ISSUE TITLE
Jupyter-scala kernel does not work

### ISSUE THREAD

**Issue by fikovnik** [willwhitney/hydrogen#121] opened 2015-10-15 20:39 UTC
It seems that [jupyter-scala](https://github.com/alexarchambault/jupyter-scala) does not work in hydrogen.

I installed the jupyer-scala as described on its github site and verified it works with ipython.
In hydrogen settings I tried to map the scala language to scala211: `{"Scala":"scala211"}`

But then I get the following error:

```
[Enter steps to reproduce below:]
**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [hydrogen](https://github.com/willwhitney/hydrogen) package, vundefined


### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined


At /Users/krikava/.atom/packages/hydrogen/lib/watch-sidebar.coffee:10

TypeError: Cannot read property 'name' of undefined
  at new WatchSidebar (/Users/krikava/.atom/packages/Hydrogen/lib/watch-sidebar.coffee:10:59)
  at new Kernel (/Users/krikava/.atom/packages/Hydrogen/lib/kernel.coffee:23:29)
  at Object.module.exports.KernelManager.startKernel (/Users/krikava/.atom/packages/Hydrogen/lib/kernel-manager.coffee:121:22)
  at /Users/krikava/.atom/packages/Hydrogen/lib/main.coffee:255:44
  at /Users/krikava/.atom/packages/Hydrogen/lib/config-manager.coffee:23:13
  at Object.module.exports.portfinder.findManyHelper (/Users/krikava/.atom/packages/Hydrogen/lib/find-port.coffee:21:13)
  at /Users/krikava/.atom/packages/Hydrogen/lib/find-port.coffee:26:18
  at Server.<anonymous> (/Users/krikava/.atom/packages/Hydrogen/lib/find-port.coffee:14:21)
  at Server.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitCloseNT (net.js:1495:8)
  at doNTCallback1 (node.js:427:9)
  at process._tickCallback (node.js:349:17)


### Commands


     -0:39 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:30.8.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:17.8.0 core:move-left (atom-text-editor#Hydrogen.languageMappings.editor.mini.is-focused)
     -0:15.1.0 core:move-right (atom-text-editor#Hydrogen.languageMappings.editor.mini.is-focused)
     -0:13.9.0 core:move-left (atom-text-editor#Hydrogen.languageMappings.editor.mini.is-focused)
     -0:11.6.0 core:move-right (atom-text-editor#Hydrogen.languageMappings.editor.mini.is-focused)
     -0:10.8.0 core:save (atom-text-editor#Hydrogen.languageMappings.editor.mini.is-focused)
     -0:07.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 set-syntax:Scala (atom-text-editor.editor)
     -0:03.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.5.0 hydrogen:run (atom-text-editor.editor.is-focused)

### Config

{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}

### Installed Packages

# User
Hydrogen, v0.6.3
autocomplete-paths, v1.0.2
ever-notedown, v0.2.11
file-type-icons, v0.7.3
language-latex, v0.6.1
language-scala, v1.1.3
latex, v0.26.0
open-recent, v2.3.0
set-syntax, v0.3.0

# Dev
No dev packages
```

Then I just changed the kernel settings and retied, This time it hangs while Atom is eating all the CPU.
I see "scala kernel: starting", but nothing happens. Neither seems to do any interrupt and restart actions.

**Comment by n-riesco** [comment] 2015-10-16 08:02
On 15/10/15 21:39, Filip Krikava wrote:
> I installed the jupyer-scala as described on its github site and verified it works with ipython.
> In hydrogen settings I tried to map the scala language to scala211: |{"Scala":"scala211"}|

I think it should be the other way around: |{"scala211":"scala"}|

I don't know why Hydrogen doesn't complain it can't find a kernel.

**Comment by terraqout** [comment] 2015-10-16 11:51
look to kernel errors in developer console, it should help

**Comment by willwhitney** [comment] 2015-10-17 18:19
OK, I figured out what's going on. The end result is that Hydrogen is asking Atom for a grammar named "scala211", and of course there isn't one. This is my bad. 20265df2619dfd3a354be52b8652431637bd5ae7 fixes this problem.

However, I'm trying to get the Scala kernel running in Hydrogen right now, and it seems to really not ever send a message beyond saying it's starting. It works in the notebook, though. I'm not sure what difference between Hydrogen and the notebook causes this. Perhaps the kernel is sending information on the wrong channel?

**Comment by willwhitney** [comment] 2015-10-17 18:20
[14:12:35] will@MacBook-Pro /Users/will/code/hydrogen/ (master|✔ ) $ apm publish patch
Preparing and tagging a new version ✓
Pushing v0.6.4 tag ✓
Publishing Hydrogen@v0.6.4 ✓

**Comment by tylerprete** [comment] 2015-10-30 00:15
@willwhitney were you able to resolve this?

**Comment by sbromberger** [comment] 2015-12-10 16:00
I'd love to get this working as well, but developer console just shows kernel starting, and that's it. Any update?

**Comment by terraqout** [comment] 2015-12-12 11:50
@sbromberger @tylerprete even if hydrogen is patched to find scala211 kernel didn't answer after starting event as was mentioned here: https://github.com/willwhitney/hydrogen/issues/121#issuecomment-148939094. You can test this behavior — just change your kernel json to

```{
 "language" : "scala",
  "display_name" : "Scala 2.11",
...
```

So this is kernel specific bug, try to creating issue on it's own page.

**Comment by sbromberger** [comment] 2015-12-12 15:39
@terraqout I got the kernel association working by putting `{"scala211": "scala"}` in the Hydrogen Language Mappings. That's not the issue. The issue is https://github.com/willwhitney/hydrogen/issues/121#issuecomment-148939094 - are you suggesting that this is a kernel issue and not a Hydrogen issue?

**Comment by terraqout** [comment] 2015-12-12 16:11
yes its kernel specific

**Comment by willwhitney** [comment] 2016-01-04 03:15
Closing this as an issue with the kernel.

**Closed by willwhitney** 2016-01-04 03:15 UTC

**Comment by rgbkrk** [comment] 2017-04-25 05:18
Just a note that I was able to use `jupyter-scala` with Hydrogen. One extra thing you need to do is install the `language-scala` package.
