### ISSUE TITLE
No visible output/results

### ISSUE THREAD

**Issue by andre-dietrich** [willwhitney/hydrogen#73] opened 2015-07-02 19:31 UTC
Hi, first of all, great tool... And actually it also seems to work for me with Python, but the problem that I have is that I do not get visible results. After every command there is only a check mark, but I do not see any output of a print, a loop, a variable, matplotlib, etc. ... only the check marks ... Any hints?

Thanks in advance...

**Comment by willwhitney** [comment] 2015-07-02 19:37
Some people have reported that they have to save the file first (#53).

Otherwise, can you pop open the developer console in Atom (View > Developer > Developer tools) and show me what you get?

**Comment by andre-dietrich** [comment] 2015-07-02 19:48
Hi, it is saved ... I hope the screenshot helps...

![bildschirmfoto vom 2015-07-02 21 45 13](https://cloud.githubusercontent.com/assets/3089101/8486275/e30f4094-2103-11e5-81b0-903cf2d650c1.png)

**Comment by willwhitney** [comment] 2015-07-02 19:53
Can you pop down the `shell message: ▶ Object`s that come before `resultType after update: null`?

It looks like it's not receiving some IO messages from the kernel, but let's see what those shell messages say.

**Comment by andre-dietrich** [comment] 2015-07-02 19:59
![bildschirmfoto vom 2015-07-02 21 57 35](https://cloud.githubusercontent.com/assets/3089101/8486541/86a7c342-2105-11e5-887a-ab0d55ed859b.png)

**Comment by willwhitney** [comment] 2015-07-02 20:05
Hmm, yeah, it seems like somehow ZeroMQ is just not connected on the IO ports. Does this always happen (i.e. across restarts)? And I assume that you do get results displayed when you use the `ipython notebook`?

**Comment by andre-dietrich** [comment] 2015-07-02 20:13
In ipython everything works fine ... The strange thing is (probably it is not strange at all, except for me) that I it seems to work for assertions...

![bildschirmfoto vom 2015-07-02 22 09 23](https://cloud.githubusercontent.com/assets/3089101/8486722/0e8e3c72-2107-11e5-9c4c-39ed453f9ee7.png)

It is always the same, also during restarts ...

**Comment by willwhitney** [comment] 2015-07-02 20:28
Yeah, errors come in on the shell message socket.

@rgbkrk any insights on this?

**Comment by andre-dietrich** [comment] 2015-07-03 09:28
After some googling I found out, that jupiter uses a new message format... I downgraded to the standard ubuntu version of ipython notebook ... and ... your nice plugin worked out of the box :.).

**Comment by ChrislS** [comment] 2015-07-03 12:07
I can confirm the issue with IPython 3.2 (default anaconda installation). I did not try @andre-dietrich s solution, because I didn't want to mix my system and anaconda python installations.

**Comment by rgbkrk** [comment] 2015-07-03 17:42
No idea, though on the surface this looks like a lack of handling old versions of the message spec (Hydrogen is hardcoded to 5.0 with some adapting to various quirks).

**Comment by rgbkrk** [comment] 2015-07-03 17:52
On a side note, I've had to delete old kernels and reinstall them to get them to work with Hydrogen (not wanting to dive deep into why, just moving forward with the future).

**Comment by willwhitney** [comment] 2015-07-03 18:32
Looks like @andre-dietrich is running IPython 3.2, so I don't think this should be an issue with an old message spec.

And that's super weird. Maybe they didn't write kernelspecs initially?

**Comment by willwhitney** [comment] 2015-07-07 19:21
Closing this because I don't *think* this is actually a Hydrogen problem — someone please correct me if I'm wrong / you know what's causing this.

**Closed by willwhitney** 2015-07-07 19:21 UTC

**Comment by ChrislS** [comment] 2015-07-07 21:16
I tried on three computers now and could not get hydrogen to work on either one. They were always using Anaconda Python as distribution, but the ipython version varies between 3.1 and 3.2. Atom version is 1.0, the OS is Ubuntu Linux 14.04 with stock `libzmq-dev` installed. If it's not hydrogen related, how could we then narrow down on where the issue comes from?

**Comment by willwhitney** [comment] 2015-07-07 21:40
But this does work with non-Anaconda IPython?

**Comment by ChrislS** [comment] 2015-07-09 20:32
This is not an option for me, since I need some Anaconda-specific packages. What would be the best way to debug things or narrow down the bug? Is there any troubleshooting website, etc.?

**Comment by ChrislS** [comment] 2015-07-10 08:36
Finally solved this:
the reason is for the lacking output is, that Anaconda provides its own version of libzmq, which is not on the system path or the ld_library_path. When building hydrogen, it complains about the missing zmq libs and asks the user to install them. When doing so, there is a version mismatch between the system and Anaconda's libzmq.

When now hydrogen instantiates the Anaconda IPython kernel, the kernel uses its own, newer libzmq, but hydrogen relies on its older system-libzmq, leading to problems.

My solution was to remove the system libzmq and build a new, current version by hand. Looking back in retrospoective, it is even 'cleaner' to create symlinks to the libzmq provided by Anaconda. I don't know whether there is a good way to check for this scenario within hydrogen, but it might be worthwhile adding this failure case to a FAQ or similar...

Thank you for the fast responses and the great project!

**Comment by andre-dietrich** [comment] 2015-07-10 10:06
@ChrislS :+1:  thanks for this comment, it worked for me too

**Comment by willwhitney** [comment] 2015-07-13 16:05
Awesome work, @ChrislS! I'm putting together a troubleshooting page and this is definitely going on there.

**Comment by rgbkrk** [comment] 2015-07-13 17:32
If we're able to make cleaner symlinks to the libzmq provided by Anaconda (or even pyzmq), that might be a *great* thing to add to node-zmq.

/cc @minrk

**Comment by worldsayshi** [comment] 2015-09-08 14:51
I had the same problem (ubuntu). Seemed like the problem was that I had installed the old `libzmq-dev`. Seems like I solved the problem by first installing `libzmq3-dev` and then reinstalling hydrogen. 

Also remember to restart atom from command line afterwards.

**Comment by worldsayshi** [comment] 2015-09-08 14:57
Probable duplicate: https://github.com/willwhitney/hydrogen/issues/88

**Comment by n-riesco** [comment] 2015-09-08 16:34
`libzmq-dev` works for me in Ubuntu 14.04 (with jupyter installed using pip).

**Comment by n-riesco** [comment] 2015-09-08 17:04
I've just checked the following configurations:
- this issue is not present in an installation with ubuntu 14.04, jupyter and libzmq-dev
- this issue is present in an installation with ubuntu 14.04, ipython 1.2.1, libzmq-dev (the issue disappears after installing libzmq3-dev)

**Comment by DraceniY** [comment] 2018-04-17 19:02
Hey, i have same problem no output 
![issue_hydrogen](https://user-images.githubusercontent.com/25039701/38890732-3d257718-4250-11e8-9cfb-810a0f2f0d64.png)

**Comment by n-riesco** [comment] 2018-04-18 16:07
@DraceniY It doesn't look like you're using Hydrogen. Please, could you open a new issue and describe the steps to reproduce the problem?
